### ISSUE TITLE
Please make Apple universal binaries for intel/M1

### ISSUE THREAD

**Issue by devleaks** [TwinFan/XPPlanes#1]
Hello,
Could you please take a few minutes to compile XPPlanes for both Apple intel and M1 architectures?
Many thanks.
Best regards.
P.

**Comment by devleaks** [comment]
At the same time, could you please update the docker process to generate universal binaries.
That way we would be able to generate plugins ourselves... Thank you.

**Comment by TwinFan** [comment]
Thanks or your interest in XPPlanes. It is in fact the first time I get some feedback about anybody using it.

Please find attached here a universal binary for mac.
[XPPlanes_mac_universal.zip](https://github.com/TwinFan/XPPlanes/files/9547533/XPPlanes_mac_universal.zip)

I am not currently allowed to update public places with the updated X-Plane library (XPLM). This will only become possible once the `400` version of XPLM required for ARM compilation has been [officially published](https://developer.x-plane.com/sdk/plugin-sdk-downloads/).

I think I figured a way to produce the universal image with Docker/osxcross. So once I am allowed to upload XPLM I will update the repository.

I continue to build the public images with GitHub actions as they run natively on Apple and also allow to include the signature and notarisation process.

**Comment by devleaks** [comment]
Thank you so much for recompiling xpplanes.
I had a quick look at osxcross, and it can, apparently cross compile for arm64 too. If it does not generate universal binaries, you can always combine a x86_64 binary and an arm64 binaries with lipo(1) on macOS.
Best regards. Pierre
