### ISSUE TITLE
Describe a Way to add FMOD .snd File to CSL model

### ISSUE THREAD

**Issue by NCC21864** [TwinFan/XPPlanes#5]
I Have build a XPPlanes With FMOD,but now I can't find any way to add my custom fmod file to csl model,wondering the informations,3ks

**Comment by TwinFan** [comment]
There is none. X-Plane's [`.obj` file format](https://developer.x-plane.com/article/obj8-file-format-specification/) does not allow for inclusion of sound. The [`.snd` file](https://developer.x-plane.com/article/sound-snd-file-format-specification/) only applies to proper aircraft  a user can fly, not to objects. This is an X-Plane limitation.

The sound produced by XPPlanes (with the help of XPMP2) is produced directly by the plugin, calling FMOD directly, not controlled through the CSL model. If you want to influence the sounds played you would need to implement your own derivation of the `XPMP2::Aircraft` class as outline in the [XPMP2 Sound documentation](https://twinfan.github.io/XPMP2/Sound.html#default-sounds).
