### ISSUE TITLE
MSVC

### ISSUE THREAD

**Issue by NCC21864** [TwinFan/XPPlanes#6]
Hello Twinfan,

I encountered an issue while using Visual Studio to build your project. If the computer where the plugin is installed does not have the MSVC or other C++ runtime libraries installed, the plugin reports an error and fails to run due to missing libraries. I would like to know how to configure the build settings in Visual Studio so that the plugin can be used on all computers.

**Comment by TwinFan** [comment]
It won't work without the runtime libraries. Professional software brings them as part of the installation process. Here you'll need to go manually.

For example my [LiveTraffic instructions](https://twinfan.gitbook.io/livetraffic/introduction/requirements) say:

> A recent version the "Visual C++ Redistributable for Visual Studio 2019" is required for LiveTraffic to run on Windows. It is often available already, but not necessarily up-todate. Find a Microsoft [support article here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads). Download and install [vc_redist.x64.exe](https://aka.ms/vs/17/release/vc_redist.x64.exe).
If LiveTraffic doesn't start and Log.txt contains 
LiveTraffic.xpl : Error Code = 1114 : A dynamic link library (DLL) initialization routine failed.
then most likely you're missing this redistributable or it is not up-to-date.
