### ISSUE TITLE
Issue with sending traffic as array

### ISSUE THREAD

**Issue by Kriso23** [TwinFan/XPPlanes#7]
Hi there,
I'm having issues sending my traffic over in a JSON array. When I send each JSON object one by one then it works perfect but as mentioned in the readme it would be more efficient to send it in an array. 

I get this error in the log:
`0:18:42.799 XPPlanes WARN  FD_XPPTraffic.cpp:108/FillFromXPPTraffic: JSON record is missing the id attribute or the position object`

and this is the code I am using:
![image](https://github.com/user-attachments/assets/9ad6e8d4-0eb3-4e83-9a05-3466369c3332)

Perhaps somebody can spot my error? Is it something to do with the new lines? the JSON array is in a single line.

Here is an example JSON array from my script which I checked with an online json formatter and it was valid:
`[{"id": "AUA001", "position": {"lat": 47.50022682642991, "lon": -52.33997493748746, "alt_geo": 32000, "gnd": false, "timestamp": 0}},{"id": "AUA002", "position": {"lat": 47.50079937289065, "lon": -53.36451338746164, "alt_geo": 32000, "gnd": false, "timestamp": 0}},{"id": "AUA003", "position": {"lat": 47.53442284951419, "lon": -52.379425735701396, "alt_geo": 32000, "gnd": false, "timestamp": 0}},{"id": "AUA004", "position": {"lat": 49.50021679929566, "lon": -52.360168171985656, "alt_geo": 32000, "gnd": false, "timestamp": 0}},{"id": "AUA005", "position": {"lat": 49.5007858211901, "lon": -53.36571839575732, "alt_geo": 32000, "gnd": false, "timestamp": 0}},{"id": "AUA006", "position": {"lat": 49.50135527046953, "lon": -54.36572847318828, "alt_geo": 32000, "gnd": false, "timestamp": 0}},{"id": "AUA007", "position": {"lat": 49.501919752618065, "lon": -55.36574423664128, "alt_geo": 32000, "gnd": false, "timestamp": 0}},{"id": "AUA008", "position": {"lat": 49.50248446291213, "lon": -56.365481549087164, "alt_geo": 32000, "gnd": false, "timestamp": 0}},{"id": "AUA009", "position": {"lat": 49.50305535495292, "lon": -57.364839913805135, "alt_geo": 32000, "gnd": false, "timestamp": 0}}]`

Thanks in advance for any help!

**Comment by TwinFan** [comment]
The `id` field is supposed to be numeric or, if it is a string, then it is supposed to be a hex value. It is modelled after an ADS-B transponder id.

In your data, the `id` looks more like a call sign.

**Comment by Kriso23** [comment]
ah gotcha, how would I go about converting the callsign to a hex value? Is there a function for that? the python hex() function only works for integers. thanks for the reply!

**Comment by TwinFan** [comment]
The idea was that if you are _generating_ traffic then you'd generate some kind of unique identifier anyway, which you would send in the `id` field.

A callsign isn't exactly uniquely identifying a plane anyway. I don't know your usecase...if the most unique thing you have in your hand is the call sign then just turn it numeric by interpreting it as a base-36 number (26 letters plus 10 digits) using [Python's `int(value radix)` function](https://docs.python.org/3.13/library/functions.html#int) with `radix=36`. So
```
int('AUA001', 36)
```
should return `655516801` (try it [here](https://www.unitconverters.net/numbers/base-36-to-base-10.htm)), and that number can go into the `id` field as a numeric value. And the callsign as text into the `ident/call` field.

**Comment by Kriso23** [comment]
cool, thanks! will try that
